# Generated by Django 5.2.5 on 2025-08-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='posted_to_ledger',
            field=models.BooleanField(default=False),
        ),
    ]
